name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: ls -la
      - run: docker build -t servicea:$(date +%s) . --file ./SOA/micro-services/ServiceA.Dockerfile
      - run: docker build -t serviceb:$(date +%s) . --file ./SOA/micro-services/ServiceB.Dockerfile
      - run: docker build -t serverapp:$(date +%s) . --file ./SOA/micro-services/Server.Dockerfile
      - run: echo "One last message"
